# Generated by Django 5.2.6 on 2025-09-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_note_content_alter_subtask_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.category'),
        ),
    ]
